# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'autonomous-driving-app' do
	pod 'CocoaAsyncSocket'  
end

target 'autonomous-driving-appTests' do

end

target 'autonomous-driving-appUITests' do

end

